spring.application.name=tiendaenfoque

spring.datasource.url=jdbc:mysql://localhost:3306/tiendaenfoque1
spring.datasource.username=root
spring.datasource.password=Silvaneins77@


spring.jpa.hibernate.ddl-auto=update


